In [1]:
import numpy as np

1、创建一个长度为10的一维全为0的ndarray对象，然后让第五个元素等于1

In [4]:
n = np.zeros(10,dtype=np.int64)
n[4] = 1
n

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2、创建一个元素从10到49的ndarray对象

In [6]:
n = np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3、将第2题的所有元素位置反转

In [9]:
n2 = n[::-1]
n2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [14]:
n = np.random.random(size=(10,10))
display(n,np.max(n),np.min(n))

array([[0.91877483, 0.12810952, 0.5598882 , 0.07216867, 0.33859926,
        0.44720348, 0.3558516 , 0.43582802, 0.10724812, 0.80963649],
       [0.2715623 , 0.90764249, 0.23710886, 0.07653112, 0.25155319,
        0.52132011, 0.65445133, 0.44157748, 0.4761217 , 0.74902366],
       [0.5827603 , 0.85709554, 0.82831716, 0.84518798, 0.69435983,
        0.11054649, 0.4097011 , 0.99336495, 0.75771081, 0.85156584],
       [0.5155193 , 0.7502837 , 0.84894493, 0.27691725, 0.37681569,
        0.60870057, 0.88294066, 0.33122277, 0.31871818, 0.98028369],
       [0.87447964, 0.89666902, 0.74068459, 0.67232005, 0.05293478,
        0.33772978, 0.37290943, 0.99834654, 0.78376847, 0.77903692],
       [0.42936128, 0.4831665 , 0.80589549, 0.22964608, 0.65251903,
        0.68054296, 0.12943641, 0.46513535, 0.15793307, 0.09138126],
       [0.28891781, 0.66075873, 0.51500057, 0.07329753, 0.01763364,
        0.20444946, 0.64614017, 0.47708294, 0.50179555, 0.63914421],
       [0.27848096, 0.67152805, 0.1396181

np.float64(0.9983465449211046)

np.float64(0.012316572402837345)

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [22]:
n = np.zeros(shape=(10,10), dtype=np.int64)
n[[0,-1]] = 1
n[:,[0,-1]]=1
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [25]:
n2 = np.ones(shape=(10,10),dtype=np.int64)
n2[1:-1,1:-1] = 0
n2

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

6、创建一个每一行都是从0到4的5*5矩阵

In [26]:
l = [0,1,2,3,4]
n = np.array(l*5).reshape(5,5)
n

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

7、创建一个范围在(0,1)之间的长度为12的等差数列

In [27]:
n = np.linspace(0,1,12)
n

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8、创建一个长度为10的随机数组并排序

In [35]:
n = np.random.randint(0, 10, size=10)
np.sort(n)
n

array([7, 6, 6, 8, 0, 1, 8, 6, 3, 6], dtype=int32)

9、创建一个长度为10的随机数组并将最大值替换为0

In [36]:
n = np.random.randint(0, 10, size=10)
n

array([8, 3, 8, 8, 9, 7, 7, 1, 3, 5], dtype=int32)

In [38]:
# 第一个最大值设置为0
n[np.argmax(n)] = 0
n

array([0, 3, 8, 8, 0, 7, 7, 1, 3, 5], dtype=int32)

In [42]:
# 所有最大值设置为0
n2 = np.argwhere(n==np.max(n)).reshape(-1)
n[n2] = 0
n

array([0, 3, 0, 0, 0, 7, 7, 1, 3, 5], dtype=int32)