In [1]:
import numpy as np

1、给定一个4维矩阵，如何得到最后两维的和？

In [4]:
n = np.random.randint(0,10,size=(2,3,4,5))
n
n.sum(axis=(2,3))
# axis=0表示第一个维度
# axis=1表示第二个维度
# axis=2表示第三个维度
# axis=3表示第四个维度

array([[ 90,  89,  76],
       [111, 104,  90]])

2、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [9]:
n = np.arange(1,6)
n2 = np.zeros(17, dtype=np.int64)
n2[::4] = n
n2

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

3、给定一个二维矩阵，如何交换其中两行的元素？

In [14]:
n = np.random.randint(0,10,size=(4,4))
n

array([[2, 8, 6, 4],
       [7, 2, 6, 5],
       [5, 4, 7, 9],
       [4, 1, 0, 0]], dtype=int32)

In [16]:
# 使用索引交换行
n2 = n[[1,0,2,3]]
n2

array([[7, 2, 6, 5],
       [2, 8, 6, 4],
       [5, 4, 7, 9],
       [4, 1, 0, 0]], dtype=int32)

4、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

In [18]:
n = np.random.randint(0,10,size=100000)
n

array([5, 6, 3, ..., 9, 7, 3], shape=(100000,), dtype=int32)

In [25]:
%timeit n ** 3

119 μs ± 1.09 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [24]:
%timeit np.power(n,3)

118 μs ± 4.72 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


5、创建一个5 * 3随机矩阵和一个3 * 2随机矩阵，求矩阵积

In [26]:
n1 = np.random.randint(0,10,size=(5,3))
n2 = np.random.randint(0,10,size=(3,2))
n1,n2

(array([[6, 6, 1],
        [1, 1, 8],
        [5, 6, 4],
        [2, 4, 5],
        [3, 8, 7]], dtype=int32),
 array([[7, 7],
        [7, 4],
        [1, 3]], dtype=int32))

In [28]:
n1.dot(n2)

array([[85, 69],
       [22, 35],
       [81, 71],
       [47, 45],
       [84, 74]], dtype=int32)

6、矩阵的每一行的元素都减去该行的平均值

In [29]:
n = np.random.randint(0,10,size=(5,3))
n

array([[7, 1, 9],
       [6, 7, 9],
       [7, 8, 4],
       [8, 7, 9],
       [1, 9, 6]], dtype=int32)

In [45]:
n2 = n.mean(axis=1).reshape(5,1)
n-n2

array([[ 1.33333333, -4.66666667,  3.33333333],
       [-1.33333333, -0.33333333,  1.66666667],
       [ 0.66666667,  1.66666667, -2.33333333],
       [ 0.        , -1.        ,  1.        ],
       [-4.33333333,  3.66666667,  0.66666667]])

7、打印出以下矩阵（要求使用np.zeros创建8*8的矩阵）：

    [[0 1 0 1 0 1 0 1],
     [1 0 1 0 1 0 1 0],
     [0 1 0 1 0 1 0 1],
     [1 0 1 0 1 0 1 0],
     [0 1 0 1 0 1 0 1],
     [1 0 1 0 1 0 1 0],
     [0 1 0 1 0 1 0 1],
     [1 0 1 0 1 0 1 0]],

In [46]:
n = np.zeros(shape=(8,8),dtype=np.int64)
n

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
n[::2,1::2] = 1
n[1::2,::2] = 1
n

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

8、正则化一个5*5随机矩阵
- 正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)

In [52]:
n = np.random.randint(0,10,size=(5,5))
n

array([[4, 4, 7, 1, 8],
       [5, 3, 9, 2, 4],
       [3, 1, 2, 6, 2],
       [3, 3, 1, 6, 7],
       [5, 7, 0, 8, 0]], dtype=int32)

In [54]:
max=np.max(n)
min=np.min(n)
max,min

(np.int32(9), np.int32(0))

In [56]:
# 归一化
(n - min)/(max - min)

array([[0.44444444, 0.44444444, 0.77777778, 0.11111111, 0.88888889],
       [0.55555556, 0.33333333, 1.        , 0.22222222, 0.44444444],
       [0.33333333, 0.11111111, 0.22222222, 0.66666667, 0.22222222],
       [0.33333333, 0.33333333, 0.11111111, 0.66666667, 0.77777778],
       [0.55555556, 0.77777778, 0.        , 0.88888889, 0.        ]])